import { DesignVariation } from "@/lib/types";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { GeneratedFlyer } from "@/lib/types";
import { CheckCircle } from "lucide-react";
import { MultiColorLoading } from "@/components/ui/multi-color-loading";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";

type DesignSuggestionsProps = {
  designs: DesignVariation[] | null;
  isGenerating: boolean;
  setGeneratedFlyer: (flyer: GeneratedFlyer | null) => void;
  setDesignSuggestions: (suggestions: DesignVariation[] | null) => void;
};

export default function DesignSuggestions({ 
  designs, 
  isGenerating, 
  setGeneratedFlyer,
  setDesignSuggestions
}: DesignSuggestionsProps) {
  const [selectedDesign, setSelectedDesign] = useState<number | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const { toast } = useToast();
  const { isAuthenticated } = useAuth();

  // Function to save design to gallery
  const saveDesignToGallery = async (design: DesignVariation) => {
    if (!isAuthenticated) return;
    setIsSaving(true);
    
    try {
      const designName = `AI Design - ${design.style}`;
      await apiRequest('POST', '/api/creations', {
        name: designName,
        imageUrl: design.imageBase64,
        headline: "AI Generated Design",
        content: `Design style: ${design.style}`,
        stylePrompt: design.style,
        template: "ai"
      });
      // Silently save - no notification displayed
    } catch (error) {
      console.error("Failed to auto-save design:", error);
      // Don't show error to user for auto-save - it happens silently
    } finally {
      setIsSaving(false);
    }
  };

  // Handle selecting a design - get the current stylePrompt from the existing flyer
  const handleSelectDesign = (design: DesignVariation) => {
    setSelectedDesign(design.id);
    
    // Create a new generated flyer from the selected design
    const newFlyer: GeneratedFlyer = {
      imageUrl: design.imageBase64,
      headline: "AI Generated Design",
      content: `Design style: ${design.style}`,
      stylePrompt: design.style, // Default to design style
      template: "ai"
    };
    
    setGeneratedFlyer(newFlyer);
    
    // Nur das erste Design beim Generieren wird in der Galerie gespeichert
    // Der FlyerPreview.tsx autoSave-Mechanismus übernimmt das Speichern
    
    // Ein Design wurde ausgewählt - keine Aktion erforderlich, da FlyerPreview.tsx es automatisch speichern wird
  };

  // Handle finalizing the design choice
  const handleUseDesign = () => {
    if (selectedDesign === null || !designs) return;
    
    // Find the selected design
    const selected = designs.find(d => d.id === selectedDesign);
    if (!selected) return;
    
    // Refresh the gallery to show newly saved designs
    queryClient.invalidateQueries({ queryKey: ['/api/creations'] });
    
    // Clear the suggestions to show only the selected design
    setDesignSuggestions(null);
  };

  if (isGenerating) {
    return (
      <div className="h-full flex flex-col">
        <div className="mb-2">
          <h2 className="text-base font-semibold text-white">Generating Designs...</h2>
        </div>
        <div className="flex-grow bg-black/20 backdrop-blur-sm rounded-xl overflow-hidden">
          <MultiColorLoading className="w-full h-full" />
        </div>
      </div>
    );
  }
  
  // Add more detailed logging about designs
  if (!designs) {
    console.error("No designs were passed to DesignSuggestions component");
    return null;
  }
  
  if (designs.length === 0) {
    console.error("Empty designs array passed to DesignSuggestions component");
    return null;
  }
  
  // Log design info for debugging
  console.log(`DesignSuggestions: Rendering ${designs.length} designs`);
  designs.forEach((design, index) => {
    console.log(`Design ${index + 1}:`, {
      id: design.id,
      hasImageBase64: !!design.imageBase64,
      base64Length: design.imageBase64 ? design.imageBase64.length : 0,
      style: design.style
    });
  });

  return (
    <div className="h-full flex flex-col">
      <div className="mb-4">
        <h2 className="text-base font-semibold text-white">Design Suggestions</h2>
        <p className="text-xs text-white/70 mb-3">
          Select one of the design variations below
        </p>
        
        {/* Explanation of the two-step process */}
        <div className="p-3 bg-indigo-500/20 border border-indigo-500/30 rounded-lg shadow-md mb-2">
          <h3 className="font-medium text-white text-sm mb-1">Design Generation Process:</h3>
          <p className="text-white/80 text-xs">
            <span className="font-medium text-indigo-300">Step 1:</span> Preview designs generated by Claude AI
            <br/>
            <span className="font-medium text-indigo-300">Step 2:</span> Select your favorite to continue to the editor for further customization
          </p>
        </div>
      </div>
      
      <div className="flex-grow flex flex-col">
        <div className={`grid ${designs.length <= 2 ? 'grid-cols-1' : 'grid-cols-2'} gap-3 grid-rows-2 h-[400px]`}>
          {designs.map((design) => (
            <div 
              key={design.id}
              className={`
                relative overflow-hidden rounded-lg border-2 cursor-pointer transition-all duration-200
                ${selectedDesign === design.id 
                  ? 'border-indigo-500 shadow-lg shadow-indigo-500/20' 
                  : 'border-gray-800/50 hover:border-indigo-500/50'}
              `}
              onClick={() => handleSelectDesign(design)}
            >
              <div className="relative aspect-square w-full flex items-center justify-center">
                {design.imageBase64 && (
                  <img 
                    src={design.imageBase64} 
                    alt={`Design option ${design.id}`}
                    className="w-full h-full object-cover"
                    onError={(e) => {
                      // Fallback if image fails to load
                      console.error(`Image load error for design ${design.id}`);
                      const target = e.target as HTMLImageElement;
                      target.onerror = null; // Prevent infinite error loop
                      target.src = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiB2aWV3Qm94PSIwIDAgMjAwIDIwMCI+PHJlY3Qgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiIGZpbGw9IiM0MzM3ZmUiLz48dGV4dCB4PSI1MCUiIHk9IjUwJSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSJ3aGl0ZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkRlc2lnbiBWb3JzY2hsYWc8L3RleHQ+PC9zdmc+';
                    }}
                  />
                )}
                
                {/* Selection indicator */}
                {selectedDesign === design.id && (
                  <div className="absolute top-2 right-2 text-indigo-500">
                    <CheckCircle size={20} />
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
        
        {selectedDesign !== null && (
          <Button
            onClick={handleUseDesign}
            className="mt-3 w-full font-medium rounded-md bg-indigo-500/40 backdrop-blur-sm text-white hover:bg-indigo-500/60 border-0"
          >
            Use Selected Design
          </Button>
        )}
      </div>
    </div>
  );
}